"""
Per-user UI state stored on the server.

Query history and remembered search fields can contain patient names and
IDs. Keeping them in the browser's localStorage would leave that data on
the workstation after logout, readable by the next person using the same
browser profile. They are stored here instead, one JSON file per user in
$PACS_DATA_DIR/user_state/ (owner-only permissions), and removed when the
user is deleted.
"""

from __future__ import annotations

import json
import logging
import os
import stat
import tempfile
import threading

logger = logging.getLogger(__name__)

ALLOWED_KEYS = ("cfind_history", "hl7_out_history", "form_fields")
MAX_VALUE_BYTES = 256 * 1024

_lock = threading.Lock()


def _state_dir() -> str:
    from config.manager import APP_DIR
    return os.path.join(APP_DIR, "user_state")


def _path(user_id: str) -> str:
    # user ids are uuid4 strings generated by web.auth; never user input
    safe = "".join(c for c in str(user_id) if c.isalnum() or c == "-")
    return os.path.join(_state_dir(), f"{safe}.json")


def load(user_id: str) -> dict:
    try:
        with open(_path(user_id), "r", encoding="utf-8") as fh:
            data = json.load(fh)
        return {k: v for k, v in data.items() if k in ALLOWED_KEYS} if isinstance(data, dict) else {}
    except FileNotFoundError:
        return {}
    except (OSError, ValueError):
        logger.warning("Could not read user state for %s", user_id, exc_info=True)
        return {}


def save_key(user_id: str, key: str, value) -> None:
    if key not in ALLOWED_KEYS:
        raise ValueError(f"Unknown state key '{key}'.")
    if len(json.dumps(value)) > MAX_VALUE_BYTES:
        raise ValueError(f"Value for '{key}' is too large.")
    with _lock:
        state = load(user_id)
        state[key] = value
        os.makedirs(_state_dir(), exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=_state_dir(), suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                json.dump(state, fh)
            try:
                os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)
            except OSError:
                pass
            os.replace(tmp, _path(user_id))
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise


def delete(user_id: str) -> None:
    with _lock:
        try:
            os.remove(_path(user_id))
        except FileNotFoundError:
            pass
